# DPE - Le dossier de ressource est packagé dans le .jar, je ne vois pas l'intérêt de mettre le fichier de docker à cet endroit-là
# De-même que votre volume
version: '3.1'
services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
